#!/usr/bin/env python3
"""
Send a test NEF-like email to yourself for testing.

Usage:
    python3 send_test_email.py your.email@gmail.com "your-app-password"

This sends a realistic NEF-format email to test the parser.
Note: The document URL won't actually download a PDF (it's a real expired link from test data).
"""
import smtplib
import sys
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText


SAMPLE_NEF_HTML = """
<div>
<p><strong><font color="#FF0000">This is an automatic e-mail message generated by the CM/ECF system.
Please DO NOT RESPOND to this e-mail because the mail box is unattended.
</font></strong></p>

<p align="center"><strong>U.S. District Court</strong></p>
<p align="center"><strong>Eastern District of TEXAS [LIVE]</strong></p>
<font face="arial,helvetica" size="3"><b>Notice of Electronic Filing</b></font>

<br><br>

The following transaction was entered on 6/10/2021 at 3:26 PM CDT<br><br>

<table cellspacing="0" border="0">
<tr><td><strong>Case Name:</strong></td><td>Alexander v. Clean Shot, LLC et al</td></tr>
<tr><td><strong>Case Number:</strong></td><td><a href="https://ecf.txed.uscourts.gov/cgi-bin/DktRpt.pl?204173">9:21-cv-00029-MJT</a></td></tr>
<tr><td><strong>Filer:</strong></td><td>Mark Henderson</td></tr>
<tr><td><strong>Document Number:</strong></td>
<td><a href="https://ecf.txed.uscourts.gov/doc1/175011894066?caseid=204173&amp;de_seq_num=37&amp;magic_num=11505292">9</a></td></tr>
</table>

<p><strong>Docket Text:</strong><br>
<font size="3" color="#0000cc" face="arial,helvetica"><b>
Joint MOTION for Extension of Time to File Settlement/Dismissal Documents by Mark Henderson.
</b></font></p>

<br>
<b>9:21-cv-00029-MJT Notice has been electronically mailed to:</b><br>
Test User &nbsp; &nbsp; test@example.com
</div>
"""

SAMPLE_NEF_TEXT = """
This is an automatic e-mail message generated by the CM/ECF system.

U.S. District Court
Eastern District of TEXAS

Notice of Electronic Filing

Case Name: Alexander v. Clean Shot, LLC et al
Case Number: 9:21-cv-00029-MJT
Filer: Mark Henderson
Document Number: 9

To view the document: https://ecf.txed.uscourts.gov/doc1/175011894066?caseid=204173&de_seq_num=37&magic_num=11505292

Docket Text:
Joint MOTION for Extension of Time to File Settlement/Dismissal Documents by Mark Henderson.
"""


def send_test_email(gmail_user, gmail_app_password):
    """Send a test NEF email to yourself."""
    msg = MIMEMultipart("alternative")
    msg["Subject"] = "Activity in Case 9:21-cv-00029-MJT Alexander v. Clean Shot - TEST"
    msg["From"] = f"ecfnotice@txed.uscourts.gov"  # Fake sender (will show as from you)
    msg["To"] = gmail_user

    msg.attach(MIMEText(SAMPLE_NEF_TEXT, "plain"))
    msg.attach(MIMEText(SAMPLE_NEF_HTML, "html"))

    print(f"Connecting to Gmail SMTP...")
    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(gmail_user, gmail_app_password)
        server.sendmail(gmail_user, gmail_user, msg.as_string())

    print(f"✓ Test email sent to {gmail_user}")
    print()
    print("Note: The email will appear in your inbox but:")
    print("  1. The 'From' address is spoofed - it will show as from you")
    print("  2. The document URL is from test data and won't download a real PDF")
    print()
    print("To test the parser, run:")
    print("  python3 nef_watcher.py")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: python3 send_test_email.py your.email@gmail.com your-app-password")
        print()
        print("Get an app password at: https://myaccount.google.com/apppasswords")
        sys.exit(1)

    send_test_email(sys.argv[1], sys.argv[2])
