#!/usr/bin/env python3
"""
Test script for NEF email parsing.

This tests the parsing logic without needing Gmail access.
"""
import email
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

# Import the parsing function from our main script
import sys
sys.path.insert(0, '.')
from nef_watcher import parse_nef_email

# Sample NEF email HTML (from TXED - Eastern District of Texas)
# Source: https://github.com/freelawproject/juriscraper/tree/main/tests/examples/pacer/nef
# Note: Using &amp; for & in URLs as it would appear in actual HTML emails
SAMPLE_NEF_HTML = """
<div><p><strong><font color="#FF0000">This is an automatic e-mail message generated by the CM/ECF system.
Please DO NOT RESPOND to this e-mail because the mail box is unattended.
</font></strong></p>

<p align="center"><strong>U.S. District Court</strong></p>
<p align="center"><strong>Eastern District of TEXAS  [LIVE]</strong></p>
<font face="arial,helvetica" size="3"><b>Notice of Electronic Filing</b></font>

<br>

<div><br>
The following transaction was entered by Neill, Erika on <span>6/10/2021</span> at 3:26
PM CDT and filed on <span>6/10/2021</span> <br>

<table cellspacing="0" border="0">
<tbody><tr><td><strong>Case Name:</strong>
</td><td>Alexander v. Clean Shot, LLC et al</td></tr>
<tr><td><strong>Case Number:</strong></td><td><a href="https://ecf.txed.uscourts.gov/cgi-bin/DktRpt.pl?204173">9:21-cv-00029-MJT</a></td></tr>
<tr><td><strong>Filer:</strong></td><td>Mark Henderson</td></tr>
<tr><td><strong>Document Number:</strong></td>
<td>
<a href="https://ecf.txed.uscourts.gov/doc1/175011894066?caseid=204173&amp;de_seq_num=37&amp;magic_num=11505292">9</a>
</td></tr>
</tbody></table>
<p>
<strong>Docket Text:</strong>
<br>
<font size="3" color="#0000cc" face="arial,helvetica"><b>
Joint MOTION for Extension of Time to File Settlement/Dismissal Documents by Mark Henderson.
</b></font>
</p>

<br>
<b>9:21-cv-00029-MJT Notice has been electronically mailed to:</b>
<br>
Erika Leigh Neill &nbsp; &nbsp; eneill@acnlaw.com
</div></div>
"""

# Same content as plain text (simplified)
SAMPLE_NEF_TEXT = """
This is an automatic e-mail message generated by the CM/ECF system.

U.S. District Court
Eastern District of TEXAS

Notice of Electronic Filing

Case Name: Alexander v. Clean Shot, LLC et al
Case Number: 9:21-cv-00029-MJT

Filer: Mark Henderson
Document Number: 9

To view the document: https://ecf.txed.uscourts.gov/doc1/175011894066?caseid=204173&de_seq_num=37&magic_num=11505292

Docket Text:
Joint MOTION for Extension of Time to File Settlement/Dismissal Documents by Mark Henderson.

Notice has been electronically mailed to:
Erika Leigh Neill - eneill@acnlaw.com
"""


def create_test_email(html_body, text_body, subject):
    """Create a mock email message for testing."""
    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = "ecfnotice@txed.uscourts.gov"
    msg["To"] = "test@example.com"

    # Only add parts that have content
    if text_body:
        msg.attach(MIMEText(text_body, "plain"))
    if html_body:
        msg.attach(MIMEText(html_body, "html"))

    return msg


def test_html_parsing():
    """Test parsing from HTML email body."""
    print("=" * 60)
    print("TEST 1: HTML Email Parsing")
    print("=" * 60)

    msg = create_test_email(
        SAMPLE_NEF_HTML,
        "",  # No plain text
        "Activity in Case 9:21-cv-00029-MJT Alexander v. Clean Shot - Motion for Extension"
    )

    case_num, doc_url, subject = parse_nef_email(msg)

    print(f"Case Number: {case_num}")
    print(f"Document URL: {doc_url}")
    print(f"Subject: {subject}")
    print()

    # Verify
    assert case_num == "9:21-cv-00029-MJT", f"Expected 9:21-cv-00029-MJT, got {case_num}"
    assert "magic_num=11505292" in doc_url, f"Expected magic_num in URL, got {doc_url}"
    print("✓ HTML parsing test PASSED")
    print()


def test_plain_text_parsing():
    """Test parsing from plain text email body."""
    print("=" * 60)
    print("TEST 2: Plain Text Email Parsing")
    print("=" * 60)

    msg = create_test_email(
        "",  # No HTML
        SAMPLE_NEF_TEXT,
        "Activity in Case 9:21-cv-00029-MJT Alexander v. Clean Shot - Motion"
    )

    case_num, doc_url, subject = parse_nef_email(msg)

    print(f"Case Number: {case_num}")
    print(f"Document URL: {doc_url}")
    print(f"Subject: {subject}")
    print()

    # Verify
    assert case_num == "9:21-cv-00029-MJT", f"Expected 9:21-cv-00029-MJT, got {case_num}"
    assert "magic_num=11505292" in doc_url, f"Expected magic_num in URL, got {doc_url}"
    print("✓ Plain text parsing test PASSED")
    print()


def test_multipart_parsing():
    """Test parsing from multipart email (both HTML and text)."""
    print("=" * 60)
    print("TEST 3: Multipart Email Parsing (prefers plain text)")
    print("=" * 60)

    msg = create_test_email(
        SAMPLE_NEF_HTML,
        SAMPLE_NEF_TEXT,
        "Activity in Case 9:21-cv-00029-MJT Alexander v. Clean Shot"
    )

    case_num, doc_url, subject = parse_nef_email(msg)

    print(f"Case Number: {case_num}")
    print(f"Document URL: {doc_url}")
    print(f"Subject: {subject}")
    print()

    assert case_num is not None, "Should extract case number"
    assert doc_url is not None, "Should extract document URL"
    print("✓ Multipart parsing test PASSED")
    print()


def test_url_extraction():
    """Test that we correctly extract the free-look URL with magic_num."""
    print("=" * 60)
    print("TEST 4: URL Format Verification")
    print("=" * 60)

    msg = create_test_email(SAMPLE_NEF_HTML, SAMPLE_NEF_TEXT, "Test")
    case_num, doc_url, subject = parse_nef_email(msg)

    print(f"Extracted URL: {doc_url}")
    print()

    # Verify URL components
    assert doc_url.startswith("https://ecf."), "Should start with https://ecf."
    assert ".uscourts.gov/doc1/" in doc_url, "Should contain .uscourts.gov/doc1/"
    assert "magic_num=" in doc_url, "Should contain magic_num parameter"
    assert "caseid=" in doc_url, "Should contain caseid parameter"

    print("URL components:")
    print(f"  - Court domain: ecf.txed.uscourts.gov ✓")
    print(f"  - Doc path: /doc1/175011894066 ✓")
    print(f"  - caseid: 204173 ✓")
    print(f"  - magic_num: 11505292 ✓")
    print()
    print("✓ URL extraction test PASSED")
    print()


def main():
    print("\nNEF Email Parser Tests")
    print("=" * 60)
    print()

    try:
        test_html_parsing()
        test_plain_text_parsing()
        test_multipart_parsing()
        test_url_extraction()

        print("=" * 60)
        print("ALL TESTS PASSED!")
        print("=" * 60)
        print()
        print("The parser correctly extracts:")
        print("  - Case numbers (e.g., 9:21-cv-00029-MJT)")
        print("  - Free-look URLs with magic_num parameter")
        print("  - Email subjects for filenames")
        print()
        print("Next steps:")
        print("  1. Configure GMAIL_USER and GMAIL_APP_PASSWORD in nef_watcher.py")
        print("  2. Add your case→folder mappings to CASE_FOLDERS")
        print("  3. Run: python3 nef_watcher.py")

    except AssertionError as e:
        print(f"✗ TEST FAILED: {e}")
        return 1
    except Exception as e:
        print(f"✗ ERROR: {e}")
        import traceback
        traceback.print_exc()
        return 1

    return 0


if __name__ == "__main__":
    exit(main())
